GET http://localhost:9090/user/

### Create new users

POST http://localhost:9090/user/
Content-Type: application/json

[{
  "username": "Ada Wong",
  "email": "AdaW@gmail.com",
  "nickname": "ada",
  "memo": "An agent.",
  "valid": true
}, {
  "username": "Leon Kennedy",
  "email": "LeonKennedy@gmail.com",
  "nickname": "leon",
  "memo": "The hero.",
  "valid": true
}]

### Update all fields for user 2
PUT http://localhost:9090/user/2
Content-Type: application/json

{
  "username": "Leon Kennedy",
  "email": "LeonKennedy@gmail.com"
}

### Update non-null fields for user 3
PATCH http://localhost:9090/user/3
Content-Type: application/json

{
  "username": "Leon Kennedy",
  "email": "LeonKennedy@gmail.com"
}

### Delete a user
DELETE http://localhost:9090/user/6

### Update for users without memo
PATCH http://localhost:9090/user/?memoNull=true
Content-Type: application/json

{
  "memo": "New memo."
}

### Delete users
DELETE http://localhost:9090/user/?memoNull=false
